### ISSUE TITLE
school recipe should add useful links to the desktop

### ISSUE THREAD

**Issue by edthedev** [edthedev/educade#1]
## Context

This recipe would be more useful if a set of web links was added to each student desktop. Sites such as `typing.com` and `mit.scratch.edu` could be added automatically. 
Initially (for the context of this issue), school lab admins could fork the repository to modify which links are included. In some future issue we can move the link list into a separate file.

## Tasks

- [ ] verify Armbian desktop manager (lightdm, I think)
- [ ] research how to add a web link to the desktop
- [ ] update the `schoolbox` role main tasks file to add some example links
